### ISSUE TITLE
[Story] DevOps

### ISSUE THREAD

**Issue by eljog** [eljog/freemarket#16]
User Story
--------
**As a** an app developer and system owner
**I want** to define DevOps pipelines for build and deployment
**so that** I can continuously deliver the product features with reliability

Acceptance Criteria
-------
**Given** the DevOps pipelines are setup
**when** the pipeline is executed
**then** the code should be deployed to the cloud environment

Tasks
-----
- [x] Setup container registry and Web app service in Azure
- [x] Create GitHub Action workflow to publish container images and deploy the app, continuously when code is checked in to main

**Comment by eddygarros** [comment]
I could help with it!

**Comment by eljog** [comment]
Hi @eddygarros I appreciate it.
Since I am developing this as part of my University capstone, at the moment I wouldn't be able to accept external contributions.

Thanks!
