### ISSUE TITLE
No error handling on login page

### ISSUE THREAD

**Issue by pranger8709** [eljog/freemarket#25]
It looks like there isn't any error handling if a user enters a username and password that does not exist or if there is an incorrect password. Below is the link to the code snippet where you want to look at. 
**Steps to Reproduce**
1. Open the Login page
2. Fill out invalid email and password
3. Click on submit
4. Nothing happens - expected an error indicating an incorrect username or password

https://github.com/eljog/freemarket/blob/395d6e394efcdc0b0f63bfa3ffd234c70a6dd2b7/src/client/webportal/src/components/login/Login.tsx#L65-L104

**Comment by eljog** [comment]
Thank you for submitting the issue. I have added this as a stretch-goal for the project
