### ISSUE TITLE
Consider renaming "Email ID" to "Email"

### ISSUE THREAD

**Issue by pranger8709** [eljog/freemarket#26]
As a user, the term "Email ID" might be confusing, consider changing it to just "Email". I think I have identified all the spots where it could be changed.

https://github.com/eljog/freemarket/blob/395d6e394efcdc0b0f63bfa3ffd234c70a6dd2b7/src/client/webportal/src/components/signup/SignUp.tsx#L160-L166

https://github.com/eljog/freemarket/blob/395d6e394efcdc0b0f63bfa3ffd234c70a6dd2b7/src/client/webportal/src/components/signup/signupValidations.ts#L68-L84

**Comment by eljog** [comment]
Thank you for taking time to review and test the product.
I have added this as a stretch-goal to the project
